#!/usr/bin/env bash
set -e

set_environment () {
	NAME=${1}
	if [[ ${NAME} =~ ^\.|/ ]]; then # it is a directory
		cd ${NAME}
		NAME=$(basename $(pwd))
		[ -s Environment ] && source Environment
		HOSTDIR="$(pwd)"
	fi
}

run_docker () {
	echo ${1}
	echo
	exec ${1}
}

case $(basename ${0}) in
    pgdock) # the script is being called as pgdock
        case ${1} in
            start|debug|console) # require a directory
                if ! [ -d ${2} ]; then
                    echo "ERROR: cluster root directory argument missing" >&2
                fi
                PGIMAGE=${PGIMAGE:-"postgres:9.6.4-alpine"}
				echo "Setting environment based on $2"
				set_environment ${2}
                [ -s Environment ] && source Environment

                DOCKERARGS="--rm \
                    --name ${NAME} \
                    --hostname ${NAME} \
                    -v ${HOSTDIR}/data:/var/lib/postgresql/data \
                    -v ${HOSTDIR}/config:/etc/postgresql \
                    -e POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}"
				[ ${HOSTPORT} ] && DOCKERARGS="${DOCKERARGS} -p ${HOSTPORT}:5432"
                PGARGS="${PGARGS} --port=5432"

                case ${1} in
                    start) MODE="-d";;
                    debug) MODE="-ti";;
                    console)
                        MODE="-ti --entrypoint=/bin/bash"
                        PGARGS="--login"
						;;
                esac
                
                echo "Initializing container ${NAME} (${PGIMAGE}) on port ${HOSTPORT}"
                run_docker "docker run ${MODE} ${DOCKERARGS} ${PGIMAGE} ${PGARGS}"
                ;;
            stop|reload|attach|logs|restart) # just need a container name for these commands
				set_environment ${2}
                case ${1} in
                    stop)
                        echo "Stopping container ${NAME}"
                        run_docker "docker kill --signal=INT ${NAME}"
                        ;;            
                    reload)
                        echo "Reloading configuration in container ${NAME}"
                        run_docker "docker kill --signal=HUP ${NAME}"
                        ;;
                    attach)
                        echo "Attaching to container ${NAME}"
                        run_docker "docker exec -ti ${NAME} /bin/bash --login"
                        ;;
                    logs)
                        echo "Showing logs from container ${NAME}"
                        run_docker "docker logs -f ${NAME}"
                        ;;
                    restart)
                        echo "Restarting container ${NAME}"
                        run_docker "docker restart ${NAME}"
                        ;;
                esac
                ;;
			install)
				TARGET=${2}
				if ! [ -d ${TARGET} ]; then
					echo "ERROR: Invalid install target directory" >&2
					exit 1
				fi
				SOURCE=${0}
				[ -h ${SOURCE} ] && SOURCE="$(readlink ${SOURCE})"
				if ! [ ${SOURCE} -ef ${TARGET}/pgdock ]; then
					echo "Installing ${TARGET}/pgdock"
					cp ${SOURCE} ${TARGET}/
				fi
				APPS=("pg_archivecleanup" \
					"pg_basebackup" \
					"pg_config" \
					"pg_controldata" \
					"pg_ctl" \
					"pg_dump" \
					"pg_dumpall" \
					"pg_isready" \
					"pg_receivexlog" \
					"pg_recvlogical" \
					"pg_resetxlog" \
					"pg_restore" \
					"pg_rewind" \
					"pg_standby" \
					"pg_test_fsync" \
					"pg_test_timing" \
					"pg_upgrade" \
					"pg_xlogdump" \
					"psql")
				for APP in ${APPS[@]}
				do
					echo "    installing ${2}/${APP}"
					ln -fs pgdock ${2}/${APP}
				done
				echo
				;;
            *)
				cat <<-EOF
					pgdock is a wrapper script for coordinating postgresql servers in docker
					and piping pg_xxx utility programs (ie. pg_dump, psql, etc.) into
					and out of a container running a postgresql database.

					Usage:  pgdock start|stop|debug|console data_dir
					        pgdock stop|restart|reload|attach|logs data_dir|container
							pgdock install bin_dir
					        bin_dir/pg_xxxx container [args]
					
					Where:  data_dir:   the directory with database "data" and "config" folders
					        container:  the name of a running container
							bin_dir:    directory to install script and related links (ie. /usr/local/bin)
					        pg_xxxx:    one of the standard postgresql utility programs
					        args:       arguments to supply to pg_xxxx
					
EOF
                ;;
        esac
        ;;
    *) # the script is being called by something other than pgdock
		COMMAND=$(basename ${0})
		set_environment ${1}
		shift
		[ -t 0 ] && ISTERM="t"
		docker exec -u postgres -${ISTERM}i ${NAME} ${COMMAND} ${@}
        ;;
esac
